# Generated by Django 4.2.11 on 2024-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_roles_alter_bill_user_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='dateofBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
