# Generated by Django 4.2.11 on 2024-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_paymenttype_alter_bill_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
