# Generated by Django 4.2.11 on 2024-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_bill_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
