# Generated by Django 4.2.11 on 2024-06-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_apartmentcardrequest_surveyrecord_remove_survey_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paymenttype'),
        ),
    ]
