# Generated by Django 4.2.11 on 2024-06-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_bill_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='type',
        ),
        migrations.AddField(
            model_name='survey',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.apartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role'),
        ),
        migrations.DeleteModel(
            name='SurveyRecord',
        ),
        migrations.DeleteModel(
            name='SurveyType',
        ),
    ]
